version: '3.9'


services:
  py:
    build:
      context: .. 
      dockerfile:
        docker/Dockerfile
    # command: []
    env_file: 
      - common.env
    image: kagemeka/etypiing-py
    network_mode: host
    restart: always
    tty: true
    volumes:
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
        read_only: false
        volume:
          nocopy: true
      - type: bind
        source: $ROOT
        target: /root/$PROJECT
        read_only: false
    working_dir: /root/$PROJECT
    command: [
      /usr/local/bin/python,
      ./src/__main__.py,
    ]

